### ISSUE TITLE
MiningDataOnline

### ISSUE THREAD

**Issue by AurelioSchug** [raiden-network/grants#2]

**Comment by czepluch** [comment]
Hey @AurelioSchug thanks for the write up. We will take a look and get back to you ASAP.

**Comment by AurelioSchug** [comment]
Hey @czepluch give me 2 more days... I will deliver!

**Comment by AurelioSchug** [comment]
Hey @czepluch please send me the link to your discord channel

**Comment by czepluch** [comment]
@AurelioSchug We don't have a discord, but we do have a gitter that you can ask questions in: https://gitter.im/raiden-network/raiden

**Comment by AurelioSchug** [comment]
@czepluch thanks for the info! Give me 5 more days. I will deliver :)

**Comment by AurelioSchug** [comment]
@czepluch sorry for the delay! I will be working full steam in the next few days in the following repository: https://github.com/MiningDataOnline/platform . I want to present a working model as soon as possible, that's why I will just make it work (just a prototype). Afterwards I will count on the community to help me make the code secure. Take care!

**Comment by AurelioSchug** [comment]
@czepluch I'm almost done with the application. The prototype and a official video-demo are almost done. I will finalize the application next Monday.
